### ISSUE TITLE
Authentication fails when Wordpress installation is not in the server root

### ISSUE THREAD

**Issue by petyabest** [perrybutler/WP-OAuth#11]
My Wordpress is installed in a subdirectory, not in the server root.
This plugin uses my server root for 'redirect_uri'. This cause that the authentication fails.

**Comment by petyabest** [comment]
I've taken a bit modification at the login-*.php files:

Changed these lines:
define('REDIRECT_URI', "http://" . rtrim($_SERVER['SERVER_NAME'], "/") . "/");
to:
define('REDIRECT_URI', get_site_url() . "/");

**Comment by perrybutler** [comment]
Thanks @peyabest, that fix was committed to the repo a few weeks ago, we just haven't rolled it out as a new version of the plugin yet. You might want to check out the recent commit from @larsschenk which contains the fix in multiple places.
