### ISSUE TITLE
should "wp_login" action also pass the $user?

### ISSUE THREAD

**Issue by bonny** [perrybutler/WP-OAuth#12]
[WordPress does also pass the $user object when calling the `wp_login` action](https://core.trac.wordpress.org/browser/tags/4.1/src/wp-includes/user.php#L92). Any change WP-OAuth could do that do, for better compatibility with other plugins (like my own [Simple History](https://github.com/bonny/WordPress-Simple-History) that uses the user object to store info about what user is being logged in).

**Comment by perrybutler** [comment]
I will check it out @bonny. Compatibility with other plugins is a high priority.

**Comment by perrybutler** [comment]
This was fixed in the latest WP-OAuth update (v0.3.1).

Before and after the fix:

![simple-history](https://cloud.githubusercontent.com/assets/3649315/6136279/3877538c-b124-11e4-89a0-6c6144bf9ae5.JPG)
