### ISSUE TITLE
Why WP oAuth reflecting my blog's IP address instead of URL in the settings page

### ISSUE THREAD

**Issue by SathyaBhat** [perrybutler/WP-OAuth#13]
While configuring Google+ signin, I noticed that at step 3, the plugin mentions IP Addres, not the blog URL

> At Google, provide your site's homepage URL (http://128.199.85.129/) for the new Project's Redirect URI

This causes problems during login request:

> Error: invalid_request

> Invalid parameter value for redirect_uri: Raw IP addresses not allowed: http://128.199.85.129/

    Request Details
    scope=profile
    response_type=code
    redirect_uri=http://128.199.85.129/
    state=54d398c5462b59.53885235

Can't seem to understand why IP address is being fetched. siteurl option in wp_options is set the to blog URL(which is https://barcampbangalore.org)

**Comment by perrybutler** [comment]
I think this issue has been fixed in the latest commit, but it hasn't been rolled out as a plugin update yet. We were using SERVER_NAME when we should have been using site_url. I'll see if we can get a plugin update pushed out today/tomorrow to the WordPress plugins directory which should hopefully resolve this. Sorry for any frustration it may be causing you.

**Comment by SathyaBhat** [comment]
Yes, I was just about to comment that this has been fixed per this PR #2

No worries, I'll wait. Thanks a lot!


 -- Sathya
http://sathyabh.at | http://sbhat.me

**Comment by perrybutler** [comment]
New version is out (v0.3). When you get a chance to test let me know how it goes!

**Comment by SathyaBhat** [comment]
Thanks Perry. It shows the site name & URL correctly now. #16 is currently a blocker for me to use the plugin though.


Nevertheless, thanks for taking the time in creating this.

**Comment by perrybutler** [comment]
Great, thanks for confirming that. #16 is a popular request, it won't be overlooked :)
