### ISSUE TITLE
choiceschances.com

### ISSUE THREAD

**Issue by tbrannam** [perrybutler/WP-OAuth#42]
FYI In Version 0.4 WP-OAuth Settings Demo link references seems to have been taken over by a spam direct.

**Comment by perrybutler** [comment]
Indeed, someone notified me the other day about it. I removed the demo link from the WordPress Plugin page already, but it is still in the Settings page. Thanks for the heads up! I'll get that removed shortly with an update probably.

**Comment by perrybutler** [comment]
Removed the demo link from the Settings page in v.4.0.1. Will restore it later.
